import type { SupabaseClient } from "@supabase/supabase-js";
import { getSession } from "@/lib/supabase/server";
import { zip } from "@/lib/zip";
import { ALLOWED_MEDIA } from "@/lib/media";
import { CAPSULE_COLUMNS, JOURNAL_COLUMNS, MEMORY_COLUMNS, MESSAGE_COLUMNS } from "@/lib/types";

export const runtime = "nodejs";
export const maxDuration = 300;

async function all(supabase: SupabaseClient, table: string, columns = "*") {
  const rows: unknown[] = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await supabase.from(table).select(columns).order("created_at").range(from, from + 999);
    if (error) throw new Error(`${table}: ${error.message}`);
    rows.push(...(data ?? []));
    if (!data || data.length < 1000) break;
  }
  return rows;
}

/** Everything you have stored, as a ZIP (default) or a single JSON file (?format=json). */
export async function GET(request: Request) {
  const { supabase, user } = await getSession();
  if (!user) return Response.json({ error: "Not signed in" }, { status: 401 });
  const format = new URL(request.url).searchParams.get("format") === "json" ? "json" : "zip";

  const [profile, memories, links, entries, conversations, messages, proposals, observations, attributes, capsules, media, letters] = await Promise.all([
    supabase.from("profiles").select("*").eq("id", user.id).single().then((r) => r.data),
    all(supabase, "memories", MEMORY_COLUMNS),
    all(supabase, "memory_links"),
    all(supabase, "journal_entries", JOURNAL_COLUMNS),
    all(supabase, "conversations"),
    all(supabase, "messages", MESSAGE_COLUMNS),
    all(supabase, "memory_proposals"),
    all(supabase, "observations"),
    all(supabase, "self_attributes"),
    all(supabase, "capsules", CAPSULE_COLUMNS),
    all(supabase, "media"),
    supabase.rpc("export_capsule_letters").then((r) => (r.data ?? []) as { id: string; letter: string }[]),
  ]);
  const letterById = new Map(letters.map((l) => [l.id, l.letter]));

  const data = {
    exported_at: new Date().toISOString(),
    format: "the-inner-world/v1",
    note: "Original text is exactly as stored. Items in `observations` and `memory_proposals` were generated by AI and are marked as such.",
    account: { id: user.id, email: user.email },
    profile,
    memories,
    memory_links: links,
    journal_entries: entries,
    conversations,
    messages,
    memory_proposals: proposals,
    ai_observations: observations,
    mirror: attributes,
    time_capsules: (capsules as { id: string }[]).map((c) => ({ ...c, letter: letterById.get(c.id) ?? "" })),
    media: (media as { id: string; mime: string }[]).map((m) => ({ ...m, file: `media/${m.id}.${ALLOWED_MEDIA[m.mime]?.ext ?? "bin"}` })),
  };
  const stamp = new Date().toISOString().slice(0, 10);
  const json = new TextEncoder().encode(JSON.stringify(data, null, 2));

  if (format === "json") {
    return new Response(json, {
      headers: {
        "content-type": "application/json",
        "content-disposition": `attachment; filename="inner-world-${stamp}.json"`,
        "cache-control": "no-store",
      },
    });
  }

  const files = [
    { name: "inner-world.json", data: json },
    {
      name: "README.txt",
      data: new TextEncoder().encode(
        `Your Inner World, exported ${new Date().toUTCString()}.\n\ninner-world.json holds every record. media/ holds your photographs and recordings; each media record in the JSON names its file.\n`,
      ),
    },
  ];
  for (const m of media as { id: string; storage_path: string; mime: string }[]) {
    const { data: blob } = await supabase.storage.from("media").download(m.storage_path);
    if (blob) files.push({ name: `media/${m.id}.${ALLOWED_MEDIA[m.mime]?.ext ?? "bin"}`, data: new Uint8Array(await blob.arrayBuffer()) });
  }
  return new Response(zip(files), {
    headers: {
      "content-type": "application/zip",
      "content-disposition": `attachment; filename="inner-world-${stamp}.zip"`,
      "cache-control": "no-store",
    },
  });
}
