// Reflection prompts are hand-written and chosen by date. They are not
// generated by AI and do not pretend to know anything about you.

export const DAILY_PROMPTS = [
  "What did you notice today that you would usually walk past?",
  "Which part of today would you happily live again?",
  "What are you carrying that isn't yours to carry?",
  "Where did you feel most like yourself this week?",
  "What is a small thing you are quietly proud of?",
  "What question have you been avoiding asking yourself?",
  "Who crossed your mind today, and why might that be?",
  "What would you tell yourself from a year ago?",
  "What does a good ordinary day look like for you right now?",
  "What changed your mind recently?",
  "What are you looking forward to, even slightly?",
  "Which promise to yourself are you keeping?",
  "What did your body try to tell you today?",
  "What would you do this week if no one were watching?",
  "What feels unfinished?",
  "What is something you understand now that you didn't before?",
  "Where is your attention going, and is that where you want it?",
  "What would make tomorrow ten percent kinder?",
  "What is a place you return to in your mind?",
  "What are you curious about lately?",
  "Which conversation is still echoing?",
  "What did you let go of, and what did that make room for?",
  "What is enough, today?",
  "What story are you telling yourself about a recent setback?",
  "When did time disappear for you recently?",
  "What would you like to remember about this season of your life?",
  "What do you need more of? Less of?",
  "What surprised you about yourself lately?",
  "Who do you want to become this year, in one sentence?",
  "What small ritual keeps you steady?",
  "What is something beautiful you saw this week?",
  "What decision is waiting for you, and what is it waiting on?",
  "What did you learn from someone younger than you?",
  "What did you do today purely for joy?",
  "What are you grateful for that you rarely mention?",
  "What does rest mean to you right now?",
  "Which fear is smaller than it looks?",
  "What would it look like to be gentler with yourself here?",
  "What idea keeps returning to you?",
  "What made you laugh recently?",
  "What do you want to protect in your life?",
  "What boundary served you well lately?",
  "What would you write on a postcard to your future self?",
  "What did the weather feel like inside you today?",
  "What is a belief you are ready to revise?",
  "What are you building, slowly?",
  "When did you last feel completely at ease?",
  "What would a wiser version of you notice about today?",
  "Which book, song or film has stayed with you, and why?",
  "What do you wish someone had asked you today?",
] as const;

function dayIndex(isoDate: string) {
  const [y, m, d] = isoDate.split("-").map(Number) as [number, number, number];
  return Math.floor(Date.UTC(y, m - 1, d) / 86400000);
}

/** The same prompt all day; a different one tomorrow. Stride avoids neighbours repeating. */
export function promptForDate(isoDate: string): string {
  const i = (dayIndex(isoDate) * 17) % DAILY_PROMPTS.length;
  return DAILY_PROMPTS[(i + DAILY_PROMPTS.length) % DAILY_PROMPTS.length]!;
}

export const DAILY_RESET_PROMPTS = [
  "How did today actually go?",
  "What mattered most?",
  "What do you want to carry into tomorrow, and what can you leave here?",
];

export const DEEP_PROMPTS = [
  "What is the thing you keep circling back to?",
  "Describe the situation as plainly as you can. Then describe how it feels.",
  "If a friend brought you this, what would you ask them?",
];

export const MOODS = ["calm", "content", "hopeful", "energised", "tender", "restless", "tired", "low", "anxious", "unsure"] as const;
